shared:
  image: node:8
jobs:
  default_true:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo test
  make_false:
    requires: [ ~pr, ~commit ]
    environment:
      SD_COVERAGE_PLUGIN_ENABLED: false
    steps:
      - echo: echo test
  default_true_ops:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo test
    environment:
      SD_SONAR_OPTS: '-Dsonar.sources=lib -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/opts/lcov.info'
  make_false_ops:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo test
    environment:
      SD_SONAR_OPTS: '-Dsonar.sources=lib -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/opts/lcov.info'
      SD_COVERAGE_PLUGIN_ENABLED: false
